### ISSUE TITLE
Redis does not bind to interfaces that are created after initial pod creation.

### ISSUE THREAD

**Issue by mtomwing** [AmadeusITGroup/Redis-Operator#39]
In our setup, pods will sometimes have extra interfaces added to their network namespaces after creation. Redis is unavailable on these new interfaces because it is bound to a static set of IPs.

https://github.com/AmadeusITGroup/Redis-Operator/blob/master/pkg/redisnode/node.go#L82

Our workaround was to replace that with `bind 0.0.0.0`.

**Comment by clamoriniere1A** [comment]
Hi @mtomwing,

#40 should allow your specific network setup. 
Let me know if it is the case, like this we can close this issue.

Regards.

**Comment by mtomwing** [comment]
This is working well for us. Thanks @clamoriniere1A!
